### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/docs#125]
I often find myself confused by the name of this repo and consider what other name would make sense.

> This repository serves as the user-facing documentation and communication space for those who are using 2i2c Hubs.

I understand this as the source to generate https://docs.2i2c.org - a static website. Perhaps we can name it `docs.2i2c.org` or append something like `mybinder.org-deploy` have done? I think the `mybinder.org-deploy` name is brilliant while I remain confused about the jupyterhub/binder repo at all times for example.

**Comment by choldgraf** [comment]
@consideRatio totally agree, it confuses me sometimes too :-)

I actually thought we might want to split this repository into 3:

1. A docs repository for **users and community representatives** of a hub who want to know best-practices in using the hub for research and education
2. A docs repository for **administrators** of a hub who want to learn how to solve problems, set up their hub, etc
3. A docs repository for **interested parties** who want to learn more about the kind of infrastructure and services we run

But maybe we shouldn't block a re-name on that restructuring?

**Comment by choldgraf** [comment]
### Proposal:

1. We rename this repository to `docs/`
2. If we want to create multiple sites, we can do so by using this as a monorepo with multiple Sphinx sites, rather than using multiple repositories.

If nobody objects to that plan in 48 hrs, then I'll do a rename of the repo@

**Comment by damianavila** [comment]
> If we want to create multiple sites, we can do so by using this as a monorepo with multiple Sphinx sites, rather than using multiple repositories.

I was going to suggest that when I saw your previous message.
