### ISSUE TITLE
Define best-practices for communities to organize themselves

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/docs#159]
### Context

Some of the communities that we serve are interested in organizing themselves more formally, defining community structure, etc. We've gotten a few questions from people about some best practices and resources that they could follow to learn more.

I don't think that our documentation should cover in-depth topics in community organization, given how much good material there is out there, but it might be useful if we provided a basic "getting started" guide along with pointers for next steps to learn more.

### Proposal

Define a few major topics that will help other communities organize themselves to be more effective / coordinated / inclusive. Add a page to our community documentation that has a section for each topic, a brief description of major considerations, and links to other websites, resources, etc for more information.

**Comment by sgibson91** [comment]
I think we should point out to resources from CSCCE as this is pretty much what they do.

**Comment by choldgraf** [comment]
Yeah I imagined a combination of CSCCE and The Turing Way for much of this, maybe some specific resources for specific topics.
