### ISSUE TITLE
Link to rstudio without knowing username?

### ISSUE THREAD

**Issue by jameshowison** [2i2c-org/docs#177]
### Context

In sending links to demos for faculty I'm encountering a few that are focused on Rstudio, but I don't seem to be able to give them a link that opens directly in Rstudio.

The documentation [/howto/environment]((../blob/main/admin/howto/environment/index.md) shows:

```
https://<your-hub>.pilot.2i2c.cloud/user/<your-username>/<your-interface>
```

Where I would just substitute `rstudio` for `<your-interface>` but I don't know people's username.  Is there a way to point them to rstudio (after their login) directly?   

Searching a bit I tried the Binder option `?urlpath=rstudio` and I tried a few other things (including leaving `<your-username> in the URL and trying random string there (reasoning that it might ask people to log in?).  I saw that directly opening a file in Rstudio via a URL is hard: https://github.com/rstudio/rstudio/issues/9925 but that shouldn't affect going to Rstudio without opening a file?

### Proposal

```
https://<your-hub>.pilot.2i2c.cloud/<your-interface>
```

(or some other predictable URL) 

should ask the user to login and take them directly to the rstudio instance (without opening a file, although clearly that would be nice in the medium term :).

**Comment by yuvipanda** [comment]
You can use `https://<your-hub>.pilot.2i2c.cloud/hub/user-redirect/<your-interface>`. Try that out? This is the format nbgitpuller uses, for example

**Comment by damianavila** [comment]
Closing as answered, please reopen if you disagree.
