### ISSUE TITLE
Add bucket docs about access - can users get bucket access from their own laptops?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/docs#179]
We have docs about [working with object storage](https://docs.2i2c.org/en/latest/data/cloud.html?highlight=scratch#working-with-object-storage) here. I think we have credentials setup for the users by a k8s ServiceAccount granted permission to read/write to those buckets we provide alongside the hub.

In [this support ticket](https://2i2c.freshdesk.com/a/tickets/322) a user wished to get access to the bucket from a laptop, but failed with `The billing account for the owning project is disabled in state absent`. I'm thinking that:

1. Maybe its because the user doesn't have access at all to the bucket?
2. Maybe its because the buckets we provide are globally accessible, but that the user must pay for the networking cost of accessing them?

I don't think the current docs provide an answer to the current status, so the action point of this issue is to clarify current status and document it in the "working with object storage" section.

**Comment by yuvipanda** [comment]
@scottyhq has a way to do this!

**Comment by scottyhq** [comment]
> @scottyhq has a way to do this! 

Yes! @yuvipanda and I prototyped something for exactly this at SciPy. Would love to move this under the 2i2c org if it's of interest to work on and integrate into deployed hubs:

https://github.com/scottyhq/jupyter-cloud-scoped-creds

**Comment by consideRatio** [comment]
Ah so my understanding is that:

1. Object storage buckets are private and not accessible without using the credentials injected to user servers
2. https://github.com/scottyhq/jupyter-cloud-scoped-creds is a way to extract AWS S3 bucket credentials specifically so that they can be used from a local laptop

**Comment by jnywong** [comment]
Closed by https://github.com/2i2c-org/docs/issues/226
