### ISSUE TITLE
Directive to replace custom Python, e.g. list of running hubs and feature tables

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/docs#212]
### Context

In my work to #207 Port existing Hub Service Guide content to Jupyter Book, I have identified that we run custom Python scripts to generate tables such as the [list of running hubs ](https://infrastructure.2i2c.org/reference/hubs/) and [feature table](https://docs.2i2c.org/about/distributions/).

### Proposal

@agoose77 suggested that we expose the tabular data as a JSON file (which is apparently already done in this [Infrastructure repo comment](https://github.com/choldgraf/pilot-hubs/blob/8de42712a106008aa817beb65e50d34778e47ce5/docs/scripts/render_hubs.py#L5-L6) - `docs/_static/hub-table.json` is published with the docs and meant for reuse in other parts of 2i2c) and then write a directive to parse this data into a table component.

Although this issue doesn't block the work in #207, exploring this direction will help with our eventual migration to using MyST in the future.

**Comment by choldgraf** [comment]
One idea here is to use a Jupyter Notebook to trigger this execution, rather than a MyST directive. Since notebooks will execute and insert content, this should basically behave the same way.

**Comment by jnywong** [comment]
Yeah, we don't think this issue will block work in #207 since my plan was to execute the Python script in some way during the build process anyway.

I think what's being proposed here is to test-drive a way for us to customise MyST components for the future.

@agoose77 let's timebox this? As I said in our meeting, there's no need for you to go down the rabbit-hole on this one :)

**Comment by jnywong** [comment]
@agoose77 feel free to close this one if it's not a priority, since I've already found a workaround in #209 👍

**Comment by agoose77** [comment]
Thanks Jenny - I was following this issue and misread the above as suggesting there was no need for a directive, hence no reply. Is that still the case? I can see a benefit to using notebook execution like this, so let me know where you settle?

**Comment by jnywong** [comment]
No worries! I think I am good, I'll close this one now
