### ISSUE TITLE
Create redirect from old customise image docs to new customise image docs

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/docs#231]
Set up redirect from https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html to https://docs.2i2c.org/admin/howto/environment/customize-image/

See https://github.com/2i2c-org/hub-user-image-template/issues/31

**Comment by choldgraf** [comment]
I suggest searching for "rediraffe" in our codebase because thats the name of the tool that we use for this 🙂

**Comment by jnywong** [comment]
Yep, that was my gameplan! 🦒
