### ISSUE TITLE
Notebook Table of Contents Request

### ISSUE THREAD

**Issue by shawnwiggins** [2i2c-org/docs#95]
Hey!

I was demonstrating something on a local notebook where I have a few extensions enabled. Several of my students on [the CCSF hub](https://ccsf.cloudbank.2i2c.cloud/) quickly noticed the Table of Contents nbextension I have enabled locally. We all agree that this would be a great feature for our hub so students can more easily navigate the larger notebooks.

Would you be able to enable that [Table of Contents (2) extension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) or something similar?

This is an enhancement and not an essential feature, so we understand if this is not high on your priority list.

Thank you for your support!

Shawn

**Comment by choldgraf** [comment]
hey @shawnwiggins - we just put together a little guide on how Hub Administrators can maintain their own user images by using the repo2docker tool - this would give you control over the environment that your users would see. Would you like to give that a shot? https://pilot.2i2c.org/en/latest/admin/howto/environment.html#bring-your-own-docker-image

**Comment by shawnwiggins** [comment]
I'll try that out. Thank you for that guide.
